app/blueprints/main/models.py
from app import db, login_manager
from datetime import datetime
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(50), unique=True)
    username = db.Column(db.String(50), unique=True)
    first_name = db.Column(db.String(50))
    last_name = db.Column(db.String(50))
    password = db.Column(db.String(250))

    def hash_my_pass(self, password):
        self.password = generate_password_hash(password)

    def check_my_pass(self, password):
        return check_password_hash(self.password, password)


class Car(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    date_created = db.Column(db.DateTime, default=datetime.utcnow)
    make = db.Column(db.String(25))
    model = db.Column(db.String(25))
    year = db.Column(db.Integer)
    color = db.Column(db.String(25))
    price = db.Column(db.Float) 
    description = db.Column(db.String(500))
    user_id = db.Column(db.Integer, db.ForeignKey("user.id"))

    def get_user(self):
        return User.query.get(self.user_id)

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

app/__init__.py
from flask import Flask, render_template
from config import Config
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager

db = SQLAlchemy()
login_manager = LoginManager()


def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)

    migrate = Migrate()
    migrate.init_app(app, db)
    db.init_app(app)
    login_manager.init_app(app)

    from app.blueprints.main import bp as main_bp

    app.register_blueprint(main_bp)

    from app.blueprints.blog import bp as blog_bp

    app.register_blueprint(blog_bp)

    from app.blueprints.auth import bp as auth_bp

    app.register_blueprint(auth_bp)

    from app.blueprints.api import bp as api_bp

    app.register_blueprint(api_bp)

    return app

app/blueprints/api/__init__.py
from flask import Blueprint

bp = Blueprint('api', __name__, url_prefix="/api/")

from . import routes

app/blueprints/api/routes.py
from flask import jsonify, request, redirect, flash, url_for
from . import bp as app
from app.blueprints.main.models import Car
from app import db
from flask_login import current_user


@app.route("/post-car", methods=["POST"])
def post_car():
    # retrieve data from request
    year = request.form["inputYear"]
    make = request.form["inputMake"]
    model = request.form["inputModel"]
    color = request.form["inputColor"]
    description = request.form["inputDescription"]
    price = float(request.form["inputPrice"])
    user = current_user.id

    # instantiate a new post
    new_sale = Car(
        year=year,
        make=make,
        model=model,
        color=color,
        description=description,
        price=price,
        user_id=user,
    )

    # add it to the database
    db.session.add(new_sale)
    db.session.commit()
    flash("New post created", "success")
    return redirect(url_for("main.home"))

app/blueprints/blog/__init__.py
from flask import Blueprint

bp = Blueprint("blog", __name__, url_prefix="/")

from . import routes

app/blueprints/blog/routes.py
from flask import render_template
from . import bp as app
@app.route("/blog")
def blog():
    return render_template("blog.html")

app/blueprints/main/__init__.py
from flask import Blueprint

bp = Blueprint("main", __name__, url_prefix="/")

from . import routes, models

app/blueprints/main/routes.py
from flask import render_template, redirect, url_for
from . import bp as app
from flask_login import current_user
from app.blueprints.main.models import Car

@app.route("/")
def home():
    if not current_user.is_authenticated: 
        return redirect(url_for("auth.login"))
    sale = Car.query.all()
    sale.sort(key=lambda sale: sale.date_created, reverse = True)

    context = { 
        "sales": sale,
        "user": "Noface"
    }
    return render_template("index.html", **context)

@app.route("/about")
def about():
    return render_template("about.html")

app/templates/about.html
{% extends "./layout.html" %} 
{%block content%}
<h1>Hello There</h1>
<h3>This is an about page</h3>
{%endblock content%}

app/templates/blog.html
{% extends "./layout.html" %}

{%block content%} 
<h1>Hello There</h1>
<h3>This is a <b>blog</b> page</h3>
{%endblock content%} 

app/templates/includes/footer.html
<h1>🏁</h1>

app/templates/includes/header.html
<nav
  class="navbar navbar-expand-sm navbar-dark"
  style="background-color: #00153b"
>
  <a class="navbar-brand" href="#">CargsList 🚙</a>
  <button
    class="navbar-toggler d-lg-none"
    type="button"
    data-toggle="collapse"
    data-target="#collapsibleNavId"
    aria-controls="collapsibleNavId"
    aria-expanded="false"
    aria-label="Toggle navigation"
  ></button>
  <div class="collapse navbar-collapse" id="collapsibleNavId">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <a class="nav-link" href="{{url_for('main.home')}}"
          >Home <span class="sr-only">(current)</span></a
        >
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{url_for('main.about')}}">About</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{url_for('blog.blog')}}">Blog</a>
      </li>
    </ul>
    <ul class="navbar-nav mt-2 mt-lg-0">
       {% if not current_user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('auth.login')}}">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('auth.register')}}">Register</a>
        </li>
        {%else%}
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('auth.logout')}}">Logout</a>
          {%endif%}
        </li> 
      </ul>
    </form>
  </div>
</nav>

app/templates/index.html
{%extends "./layout.html"%} {%block content%}
<div class="container mt-4">
  {%if current_user.is_authenticated%}
  <h1>Hello There</h1>
  <h3>Welcome to Cargslist, {{ current_user.username.title()}}.</h3>
  <div>
    <h4>Selling a car today?</h4>
  {%endif%}

    <form action="/api/post-car" method="POST">
      <div class="form-group">
        <label for="inputYear">Year</label>
        <input
          type="text"
          class="form-control"
          name="inputYear"
          id="inputYear"
        />
      </div>
      <div class="form-group">
        <label for="inputMake">Make</label>
        <input
          type="text"
          class="form-control"
          name="inputMake"
          id="inputMake"
        />
      </div>
      <div class="form-group">
        <label for="inputModel">Model</label>
        <input
          type="text"
          class="form-control"
          name="inputModel"
          id="inputModel"
        />
      </div>
      <div class="form-group">
        <label for="inputColor">Color</label>
        <input
          type="text"
          class="form-control"
          name="inputColor"
          id="inputColor"
        />
      </div>
      <div class="form-group">
        <label for="inputDescription">Description</label>
        <input
          type="text"
          class="form-control"
          name="inputDescription"
          id="inputDescription"
        />
      </div>
      <div class="form-group">
        <label for="inputPrice">Price</label>
        <input
          type="text"
          class="form-control"
          name="inputPrice"
          id="inputPrice"
        />
      </div>
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>

    {% for s in sales %}
    <div class="container">
      <div class="card m-2">
        <div class="card-body">
          <h4>{{s.year}} {{s.make}} {{s.model}}</h4>
          <h5>{{s.color}} ${{s.price}}</h5>
          <p>{{ s.description }}</p>
          <p></p>
        </div>
        <div class="card-footer d-flex justify-content-between">
          <span>{{s.get_user().username.title()}}</span>
          <span>{{s.date_created.strftime("%B %d, %Y %I:%M %p")}}</span>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  {%endblock content%}
</div>

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
    <title>Cargslist</title>
  </head>
  <body>
    <header>{%include "./includes/header.html" %}</header>
    <main>
      <div class="container">
        {% with messages = get_flashed_messages(with_categories=True) %} {% if
        messages %} {% for category, message in messages %}
        <div
          class="alert alert-{{ category }} alert-dismissible fade show"
          role="alert"
        >
          <strong>{{ message }}</strong>
          <button
            type="button"
            class="close"
            data-dismiss="alert"
            aria-label="Close"
          >
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endfor %} {% endif %} {% endwith %}
      </div>
      {%block content%}{%endblock content%}
    </main>
    <footer>{%include "./includes/footer.html" %}</footer>
    <script
      src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

app/templates/login.html
{% extends './layout.html' %} {% block content %}
<div class="container mt-4">
  <h1>Login</h1>

  <form action="/auth/login" method="POST">
    <div class="form-group">
      <label for="inputEmail">Email address</label>
      <input
        type="email"
        class="form-control"
        name="inputEmail"
        id="inputEmail"
        aria-describedby="emailHelp"
      />
    </div>
    <div class="form-group">
      <label for="inputPassword">Password</label>
      <input
        type="password"
        class="form-control"
        name="inputPassword"
        id="inputPassword"
      />
    </div>
    <p>
      Don't have an account?
      <a href="{{ url_for('auth.register') }}">Register Here.</a>
    </p>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>

{% endblock content %}

app/templates/register.html
{% extends './layout.html' %} {% block content %}
<div class="container">
  <h1>Register</h1>

  <form action="/auth/register" method="POST">
    <div class="form-group">
      <label for="inputEmail">Email address</label>
      <input
        type="email"
        class="form-control"
        name="inputEmail"
        id="inputEmail"
        aria-describedby="emailHelp"
        required
      />
    </div>
    <div class="form-group">
      <label for="inputPassword">Password</label>
      <input
        type="password"
        class="form-control"
        name="inputPassword"
        id="inputPassword"
        required
      />
    </div>
    <div class="form-group">
      <label for="inputPasswordConfirm">Confirm Password</label>
      <input
        type="password"
        class="form-control"
        name="inputPasswordConfirm"
        id="inputPasswordConfirm"
        required
      />
    </div>
    <div class="form-group">
      <label for="inputUsername">Username</label>
      <input
        type="text"
        class="form-control"
        name="inputUsername"
        id="inputUsername"
        required
      />
    </div>
    <div class="form-group">
      <label for="inputFirstName">First Name</label>
      <input
        type="text"
        class="form-control"
        name="inputFirstName"
        id="inputFirstName"
        required
      />
    </div>
    <div class="form-group">
      <label for="inputLastName">Last Name</label>
      <input
        type="text"
        class="form-control"
        name="inputLastName"
        id="inputLastName"
        required
      />
    </div>
    <p>
      Already have an account?
      <a href="{{ url_for('auth.login') }}">Login Here.</a>
    </p>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>
{% endblock content %}